## Data descriptions

---
In this competition you are predicting the probability that an online transaction is fraudulent, as denoted by the binary target isFraud.

The data is broken into two files identity and transaction, which are joined by TransactionID. Not all transactions have corresponding identity information.

Categorical Features - Transaction
ProductCD
card1 - card6
addr1, addr2
P_emaildomain
R_emaildomain
M1 - M9
Categorical Features - Identity
DeviceType
DeviceInfo
id_12 - id_38
The TransactionDT feature is a timedelta from a given reference datetime (not an actual timestamp).

You can read more about the data from this post by the competition host.

Files
train_{transaction, identity}.csv - the training set
test_{transaction, identity}.csv - the test set (you must predict the isFraud value for these observations)
sample_submission.csv - a sample submission file in the correct format

---

I see many questions regarding data description, so it maybe a better idea to open a thread for discussion. The following is a bit more details about it:

Transaction Table *

TransactionDT: timedelta from a given reference datetime (not an actual timestamp)

TransactionAMT: transaction payment amount in USD

ProductCD: product code, the product for each transaction

card1 - card6: payment card information, such as card type, card category, issue bank, country, etc.

addr: address

dist: distance

P_ and (R__) emaildomain: purchaser and recipient email domain

C1-C14: counting, such as how many addresses are found to be associated with the payment card, etc. The actual meaning is masked.

D1-D15: timedelta, such as days between previous transaction, etc.

M1-M9: match, such as names on card and address, etc.

Vxxx: Vesta engineered rich features, including ranking, counting, and other entity relations.

Categorical Features: ProductCD card1 - card6 addr1, addr2 P_emaildomain R_emaildomain M1 - M9

Identity Table *

Variables in this table are identity information – network connection information (IP, ISP, Proxy, etc) and digital signature (UA/browser/os/version, etc) associated with transactions. They're collected by Vesta’s fraud protection system and digital security partners. (The field names are masked and pairwise dictionary will not be provided for privacy protection and contract agreement)

Categorical Features: DeviceType DeviceInfo id_12 - id_38

---

In [175]:
import pandas as pd
import networkx as nx

In [176]:
train_identity = pd.read_csv('ieee-fraud-detection/train_identity.csv')
train_transaction = pd.read_csv('ieee-fraud-detection/train_transaction.csv')

In [177]:
train_identity.head()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [178]:
train_transaction.head().iloc[:, :12]

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0

# Plan for making a graph
- Many nodes: eamils, transaction id, addresses, devices, IP information (identify all of these in the two data tables and work on relating the in networkx)
- Make all edges connections from transaction to other node types

``` 
Basic example to build from
import networkx as nx

G = nx.Graph()

for _, row in df.iterrows():
    t = f"T_{row['TransactionID']}"
    card = f"C_{row['card1']}"
    
    G.add_edge(t, card)
```

In [179]:
train_identity[['id_01', 'id_02']]

        id_01     id_02
0         0.0   70787.0
1        -5.0   98945.0
2        -5.0  191631.0
3        -5.0  221832.0
4         0.0    7460.0
...       ...       ...
144228  -15.0  145955.0
144229   -5.0  172059.0
144230  -20.0  632381.0
144231   -5.0   55528.0
144232  -45.0  339406.0

[144233 rows x 2 columns]

In [180]:
def create_graph_edges_for_similar_cols(
        target_graph: nx.Graph,
        target_df: pd.DataFrame, 
        primary_node_col: str,
        primary_node_prefix: str,
        target_col_names: list[str], 
        ref_node_prefix: str, 
        ref_node_suffix: list[str] = None
    ) -> int:
    """
        This is a utility function for iterating similar columns that might need to be added to a graph in bulk. It will edit the graph passed in the argument directly.
        Retruns the size of the updated graph.

        graph: An instance of a networkx graph that needs to have connections added to it
        target_df: The data frame containing all reference columns for the mappings
        primary_node_col: The name of the column that will server as the primary node that should as the basis for many connections (ex. Transactions in a case where you want to connect many other attributes about that transaction to it),
        primary_node_prefix: A string that is the prefix for the primary node that will be used on the Graph (ex. if the primary node is Transactions you may want to use something like 'T' or 'Tr')
        target_col_names: a list of strings containing the names of columns in the target DataFrame that need to have relationships created for
        graph_label_prefix: the desired prefix for the target column to be associated with in the graph (ex if the columns are all related to credit card info you may want to use somehting like 'C')
        graph_label_suffix: this is the method for appending unique identifiers to the graph_label_prefix when there are multiple cols (once again for card info you may want something like C1, C2 ...)
                            If nothing is passed to this argument it will fill with 1 - n where n is the len of the  target_col_names. If you want custom functionality pass list of the suffix values in order.
    """
    tdf = target_df.copy() # ensure that the orginal df is not edited by this

    if ref_node_suffix != None:
        assert len(set(ref_node_suffix)) == len(ref_node_suffix), 'Graph label suffix values must be unique.'
    else: 
        ref_node_suffix = list(range(1, len(target_col_names) + 1)) # default functionality for using digits as the suffix

    for col_name, suffix in zip(target_col_names, ref_node_suffix):
        mask = tdf[col_name].notna()
        
        target_data = tdf[mask]

        connection_tuple_mappings = zip(
            f'{primary_node_prefix}_' + target_data[primary_node_col].astype('str'), 
            f'{ref_node_prefix}{suffix}_' + target_data[col_name].astype('str') # puts creates prefix of C1, C2, ... to C6 so each card identifier is unique
        )

        target_graph.add_edges_from(connection_tuple_mappings)
    
    return target_graph.size()

In [181]:
# get all connections created
# zipping the target cols as string and using add_edges_from() is more efficent so use this

# instantiate the graph
transactions_graph = nx.Graph()

# get all relevant fields that need to be added to the graph (all of this centers on transaction IDs and attributes that relate to those)
# all card data (card1 - card6)
card_cols = ['card1', 'card2', 'card3', 'card4', 'card5', 'card6']

# create card connections
create_graph_edges_for_similar_cols(
    target_graph= transactions_graph,
    target_df=train_transaction,
    primary_node_col='TransactionID',
    primary_node_prefix='Tr',
    target_col_names=card_cols,
    ref_node_prefix='C'
)

addr_cols = ['addr1', 'addr2']
# address info (addr1 and addr2 )
create_graph_edges_for_similar_cols(
    target_graph= transactions_graph,
    target_df=train_transaction,
    primary_node_col='TransactionID',
    primary_node_prefix='Tr',
    target_col_names=addr_cols,
    ref_node_prefix='Addr'
)

# identity information is next
# Looks like id_02 is the only thing that can reasonably be used without introducing a bunch of nodes with artificially high degree measures
create_graph_edges_for_similar_cols(
    target_graph= transactions_graph,
    target_df=train_identity,
    primary_node_col='TransactionID',
    primary_node_prefix='Tr',
    target_col_names=['id_02'],
    ref_node_prefix='Id'
)

4715875

In [182]:
# inspecting basic graph attributes
print(f'Number of edges: {transactions_graph.number_of_edges()}')
print(f'Number of ndoes:  {transactions_graph.number_of_nodes()}')

Number of edges: 4715875
Number of ndoes:  720895

In [183]:
from collections import Counter

# looking at the nodes by each column from the original data set
Counter(n.split('_')[0] for n in transactions_graph.nodes)

Counter({'Tr': 590540,
         'Id1': 115655,
         'C1': 13553,
         'C2': 500,
         'Addr1': 332,
         'C5': 119,
         'C3': 114,
         'Addr2': 74,
         'C4': 4,
         'C6': 4})

In [184]:
# analyzing the degree structure of the nodes

In [185]:
nodes_sorted_by_degree = sorted(list(transactions_graph.degree), key=lambda x: x[1], reverse=True)
nodes_sorted_by_degree[:20]

[('C3_150.0', 521287),
 ('Addr2_87.0', 520481),
 ('C6_debit', 439938),
 ('C4_visa', 384767),
 ('C5_226.0', 296546),
 ('C4_mastercard', 189217),
 ('C6_credit', 148986),
 ('C5_224.0', 81513),
 ('C5_166.0', 57140),
 ('C3_185.0', 56346),
 ('C2_321.0', 48935),
 ('Addr1_299.0', 46335),
 ('C2_111.0', 45191),
 ('Addr1_325.0', 42751),
 ('Addr1_204.0', 42020),
 ('C2_555.0', 41995),
 ('Addr1_264.0', 39870),
 ('C2_490.0', 38145),
 ('C5_102.0', 29105),
 ('Addr1_330.0', 26287)]

- It looks like C4 and C6 values may not be very useful here since they are generic categorical classifications that are likely to be shared and connect too many values.
- Will coninue to explore non-transaction nodes for high connectivity

In [186]:
nodes_to_explore = []

for pair in nodes_sorted_by_degree:
    non_interesting_nodes = ['Tr', 'C4', 'C6']
    node = pair[0]

    if node[:2] in non_interesting_nodes: continue

    nodes_to_explore.append(pair)

In [187]:
nodes_to_explore[:20]

[('C3_150.0', 521287),
 ('Addr2_87.0', 520481),
 ('C5_226.0', 296546),
 ('C5_224.0', 81513),
 ('C5_166.0', 57140),
 ('C3_185.0', 56346),
 ('C2_321.0', 48935),
 ('Addr1_299.0', 46335),
 ('C2_111.0', 45191),
 ('Addr1_325.0', 42751),
 ('Addr1_204.0', 42020),
 ('C2_555.0', 41995),
 ('Addr1_264.0', 39870),
 ('C2_490.0', 38145),
 ('C5_102.0', 29105),
 ('Addr1_330.0', 26287),
 ('C5_117.0', 25941),
 ('Addr1_315.0', 23078),
 ('C2_583.0', 21803),
 ('Addr1_441.0', 20827)]

In [188]:
comps = list(nx.connected_components(transactions_graph))
# [len(c) for c in comps]
sorted([len(c) for c in comps], reverse=True)
comps[1:]

[{'C1_13708', 'Id1_334674.0', 'Tr_3301059'},
 {'C1_3823', 'Id1_263916.0', 'Tr_3513119'}]

- Obviously there is some node that is connecting eeryhting leadig to only two components that are not connected to the rest.
- Will investigate the large component further using the highest degree nodes that aren't transactions from nodes_to_explore from earlier.

In [189]:
nodes_to_explore[:20]

[('C3_150.0', 521287),
 ('Addr2_87.0', 520481),
 ('C5_226.0', 296546),
 ('C5_224.0', 81513),
 ('C5_166.0', 57140),
 ('C3_185.0', 56346),
 ('C2_321.0', 48935),
 ('Addr1_299.0', 46335),
 ('C2_111.0', 45191),
 ('Addr1_325.0', 42751),
 ('Addr1_204.0', 42020),
 ('C2_555.0', 41995),
 ('Addr1_264.0', 39870),
 ('C2_490.0', 38145),
 ('C5_102.0', 29105),
 ('Addr1_330.0', 26287),
 ('C5_117.0', 25941),
 ('Addr1_315.0', 23078),
 ('C2_583.0', 21803),
 ('Addr1_441.0', 20827)]

In [190]:
# looking at transactions that are associated with this highly connected address
list(transactions_graph.neighbors('Addr1_299.0'))[:20]

['Tr_2987020',
 'Tr_2987022',
 'Tr_2987039',
 'Tr_2987045',
 'Tr_2987050',
 'Tr_2987058',
 'Tr_2987065',
 'Tr_2987081',
 'Tr_2987089',
 'Tr_2987109',
 'Tr_2987112',
 'Tr_2987116',
 'Tr_2987119',
 'Tr_2987123',
 'Tr_2987124',
 'Tr_2987127',
 'Tr_2987149',
 'Tr_2987155',
 'Tr_2987159',
 'Tr_2987163']

In [191]:
# exploring the neighbors of one transaction
list(transactions_graph.neighbors('Tr_2987020'))

['C1_7875',
 'C2_314.0',
 'C3_150.0',
 'C4_mastercard',
 'C5_224.0',
 'C6_debit',
 'Addr1_299.0',
 'Addr2_87.0']

In [192]:
# getting the 2 neighbor out sub graph for the same transaction
sub_graph = nx.ego_graph(transactions_graph, 'Tr_2987020', radius=2)

In [193]:
# inspecting the size of the sub graph
len(list(sub_graph))

575640

- It is remarkable how quickly this ballooned after the addition of one additional neighbor since all nodes associated witht this connection also have a high degree.

### Moving on to getting the transaction to transaction relationships worked out

In [194]:
# trimming the graph down to remove connections that are too deep to make bipartite transformation easier
trimmed_graph = transactions_graph.copy()

nodes_to_trim = [pair for pair in nodes_sorted_by_degree if not pair[0].startswith('Tr')]
for pair in nodes_to_trim:
    if pair[1] > 100:
        try:
            trimmed_graph.remove_node(pair[0])
        except: continue

In [195]:
from networkx.algorithms import bipartite

# fitlering down to just transaction nodes
trimmed_nodes = [node for node in trimmed_graph.nodes if node.startswith('Tr')]


# turn this into a bipartite graph where transaction nodes are all directly connected if they share other connection nodes associated with attributes
# need to do some reduction to the graph before running this, it is taking way too long
trans_to_trans_graph = bipartite.weighted_projected_graph(trimmed_graph, trimmed_nodes)

In [196]:
# looking at the most connected transactions
# weight of the edge is a direct indicaition of shared features here
sorted(
    trans_to_trans_graph.edges(data=True),
    key=lambda x: x[2]['weight'],
    reverse=True
)[:50]

[('Tr_3231907', 'Tr_3231926', {'weight': 5}),
 ('Tr_3231907', 'Tr_3231911', {'weight': 5}),
 ('Tr_3231911', 'Tr_3231926', {'weight': 5}),
 ('Tr_3004561', 'Tr_3012016', {'weight': 4}),
 ('Tr_3004561', 'Tr_3004571', {'weight': 4}),
 ('Tr_3004561', 'Tr_3012035', {'weight': 4}),
 ('Tr_3004561', 'Tr_3004589', {'weight': 4}),
 ('Tr_3004561', 'Tr_3004623', {'weight': 4}),
 ('Tr_3004571', 'Tr_3012016', {'weight': 4}),
 ('Tr_3004571', 'Tr_3012035', {'weight': 4}),
 ('Tr_3004571', 'Tr_3004589', {'weight': 4}),
 ('Tr_3004571', 'Tr_3004623', {'weight': 4}),
 ('Tr_3004589', 'Tr_3012016', {'weight': 4}),
 ('Tr_3004589', 'Tr_3012035', {'weight': 4}),
 ('Tr_3004589', 'Tr_3004623', {'weight': 4}),
 ('Tr_3004623', 'Tr_3012016', {'weight': 4}),
 ('Tr_3004623', 'Tr_3012035', {'weight': 4}),
 ('Tr_3009994', 'Tr_3010111', {'weight': 4}),
 ('Tr_3009994', 'Tr_3010002', {'weight': 4}),
 ('Tr_3010002', 'Tr_3010111', {'weight': 4}),
 ('Tr_3010656', 'Tr_3010706', {'weight': 4}),
 ('Tr_3011390', 'Tr_3011417', {'weight': 4}),
 ('Tr_3011390', 'Tr_3011418', {'weight': 4}),
 ('Tr_3011390', 'Tr_3011459', {'weight': 4}),
 ('Tr_3011417', 'Tr_3011418', {'weight': 4}),
 ('Tr_3011417', 'Tr_3011459', {'weight': 4}),
 ('Tr_3011418', 'Tr_3011459', {'weight': 4}),
 ('Tr_3012016', 'Tr_3012035', {'weight': 4}),
 ('Tr_3021885', 'Tr_3036732', {'weight': 4}),
 ('Tr_3024201', 'Tr_3024326', {'weight': 4}),
 ('Tr_3024201', 'Tr_3024318', {'weight': 4}),
 ('Tr_3024201', 'Tr_3024306', {'weight': 4}),
 ('Tr_3024306', 'Tr_3024326', {'weight': 4}),
 ('Tr_3024306', 'Tr_3024318', {'weight': 4}),
 ('Tr_3024318', 'Tr_3024326', {'weight': 4}),
 ('Tr_3031769', 'Tr_3031783', {'weight': 4}),
 ('Tr_3033504', 'Tr_3033568', {'weight': 4}),
 ('Tr_3033693', 'Tr_3033754', {'weight': 4}),
 ('Tr_3033693', 'Tr_3033786', {'weight': 4}),
 ('Tr_3033693', 'Tr_3033735', {'weight': 4}),
 ('Tr_3033735', 'Tr_3033754', {'weight': 4}),
 ('Tr_3033735', 'Tr_3033786', {'weight': 4}),
 ('Tr_3033754', 'Tr_3033786', {'weight': 4}),
 ('Tr_3092872', 'Tr_3092881', {'weight': 4}),
 ('Tr_3114168', 'Tr_3415402', {'weight': 4}),
 ('Tr_3114168', 'Tr_3114171', {'weight': 4}),
 ('Tr_3114171', 'Tr_3415402', {'weight': 4}),
 ('Tr_3140206', 'Tr_3140340', {'weight': 4}),
 ('Tr_3380544', 'Tr_3380556', {'weight': 4}),
 ('Tr_3380544', 'Tr_3380552', {'weight': 4})]

In [197]:
sorted(list(trans_to_trans_graph.degree()), key=lambda x: x[1], reverse=True)

[('Tr_3231911', 231),
 ('Tr_3231907', 230),
 ('Tr_3231926', 230),
 ('Tr_3021585', 186),
 ('Tr_3021643', 186),
 ('Tr_3023706', 186),
 ('Tr_3010766', 183),
 ('Tr_3031080', 182),
 ('Tr_3031088', 182),
 ('Tr_3014200', 178),
 ('Tr_3015164', 178),
 ('Tr_3347905', 178),
 ('Tr_3011956', 176),
 ('Tr_3057921', 176),
 ('Tr_3169705', 176),
 ('Tr_3169722', 176),
 ('Tr_3338596', 176),
 ('Tr_3057918', 175),
 ('Tr_3080639', 175),
 ('Tr_3080641', 175),
 ('Tr_3169711', 175),
 ('Tr_3169713', 175),
 ('Tr_3195485', 175),
 ('Tr_3013075', 174),
 ('Tr_3044348', 174),
 ('Tr_3014165', 173),
 ('Tr_3269745', 173),
 ('Tr_3013939', 172),
 ('Tr_3044349', 172),
 ('Tr_3046642', 172),
 ('Tr_3046652', 172),
 ('Tr_3093775', 172),
 ('Tr_3245944', 172),
 ('Tr_3417345', 172),
 ('Tr_3158125', 170),
 ('Tr_3443816', 170),
 ('Tr_3011566', 168),
 ('Tr_3061564', 168),
 ('Tr_3101695', 168),
 ('Tr_3321316', 168),
 ('Tr_3021885', 163),
 ('Tr_3036732', 163),
 ('Tr_3204864', 163),
 ('Tr_3470692', 163),
 ('Tr_3500867', 163),
 ('Tr_3544540', 163),
 ('Tr_3566576', 163),
 ('Tr_3053438', 158),
 ('Tr_3417336', 158),
 ('Tr_3010002', 157),
 ('Tr_3112647', 157),
 ('Tr_3417332', 156),
 ('Tr_3417389', 156),
 ('Tr_3550239', 156),
 ('Tr_3009994', 155),
 ('Tr_3010111', 155),
 ('Tr_3010124', 155),
 ('Tr_3032447', 154),
 ('Tr_3013912', 152),
 ('Tr_3013937', 152),
 ('Tr_2987010', 151),
 ('Tr_3044656', 151),
 ('Tr_3124438', 151),
 ('Tr_3121961', 150),
 ('Tr_3430445', 150),
 ('Tr_3444274', 150),
 ('Tr_3570117', 149),
 ('Tr_3241401', 148),
 ('Tr_3347912', 148),
 ('Tr_3004561', 146),
 ('Tr_3004589', 146),
 ('Tr_3004623', 146),
 ('Tr_3004571', 145),
 ('Tr_3012016', 145),
 ('Tr_3012035', 145),
 ('Tr_3054816', 145),
 ('Tr_3080082', 145),
 ('Tr_3095378', 145),
 ('Tr_3208372', 145),
 ('Tr_3353942', 145),
 ('Tr_3478305', 145),
 ('Tr_3077541', 144),
 ('Tr_3077601', 144),
 ('Tr_3077629', 144),
 ('Tr_3142553', 144),
 ('Tr_3147387', 144),
 ('Tr_3298089', 144),
 ('Tr_3376725', 144),
 ('Tr_3543070', 144),
 ('Tr_3551629', 144),
 ('Tr_3068177', 143),
 ('Tr_3077467', 143),
 ('Tr_3077615', 143),
 ('Tr_3077659', 143),
 ('Tr_3108756', 143),
 ('Tr_3127421', 143),
 ('Tr_3226765', 143),
 ('Tr_3227529', 143),
 ('Tr_3334226', 143),
 ('Tr_3376542', 143),
 ('Tr_3471467', 143),
 ('Tr_3478055', 143),
 ('Tr_3548033', 143),
 ('Tr_3567660', 143),
 ('Tr_3028326', 142),
 ('Tr_3019928', 140),
 ('Tr_3105912', 140),
 ('Tr_3012600', 137),
 ('Tr_3208746', 137),
 ('Tr_3232771', 137),
 ('Tr_3079428', 136),
 ('Tr_3540440', 136),
 ('Tr_3559493', 136),
 ('Tr_3559501', 136),
 ('Tr_3114168', 131),
 ('Tr_3114171', 130),
 ('Tr_3415402', 130),
 ('Tr_3026055', 129),
 ('Tr_3026407', 128),
 ('Tr_3007184', 127),
 ('Tr_3069896', 126),
 ('Tr_3097975', 126),
 ('Tr_3491955', 126),
 ('Tr_3059470', 125),
 ('Tr_3074529', 125),
 ('Tr_3553030', 125),
 ('Tr_3062380', 124),
 ('Tr_3084171', 124),
 ('Tr_3036828', 123),
 ('Tr_3042656', 123),
 ('Tr_3056183', 123),
 ('Tr_3056373', 123),
 ('Tr_3059467', 123),
 ('Tr_3101780', 123),
 ('Tr_3124924', 123),
 ('Tr_3372538', 123),
 ('Tr_3430040', 123),
 ('Tr_3396860', 122),
 ('Tr_3036355', 121),
 ('Tr_3004095', 119),
 ('Tr_3007015', 119),
 ('Tr_3008646', 119),
 ('Tr_3028098', 119),
 ('Tr_3090465', 119),
 ('Tr_3015019', 118),
 ('Tr_3034898', 118),
 ('Tr_3089960', 118),
 ('Tr_3094471', 118),
 ('Tr_3331771', 118),
 ('Tr_3446584', 118),
 ('Tr_3460624', 118),
 ('Tr_3009737', 117),
 ('Tr_3101555', 117),
 ('Tr_3110937', 117),
 ('Tr_3114635', 117),
 ('Tr_3169965', 117),
 ('Tr_3191375', 117),
 ('Tr_3274514', 117),
 ('Tr_3434819', 117),
 ('Tr_3547313', 117),
 ('Tr_3007745', 116),
 ('Tr_3020544', 116),
 ('Tr_3023168', 116),
 ('Tr_3025713', 116),
 ('Tr_3033873', 116),
 ('Tr_3055938', 116),
 ('Tr_3118957', 116),
 ('Tr_3120264', 116),
 ('Tr_3135789', 116),
 ('Tr_3136933', 116),
 ('Tr_3146988', 116),
 ('Tr_3160353', 116),
 ('Tr_3173752', 116),
 ('Tr_3180684', 116),
 ('Tr_3186839', 116),
 ('Tr_3187581', 116),
 ('Tr_3189066', 116),
 ('Tr_3191360', 116),
 ('Tr_3194263', 116),
 ('Tr_3194577', 116),
 ('Tr_3234019', 116),
 ('Tr_3249857', 116),
 ('Tr_3252415', 116),
 ('Tr_3263644', 116),
 ('Tr_3274527', 116),
 ('Tr_3319965', 116),
 ('Tr_3324580', 116),
 ('Tr_3350534', 116),
 ('Tr_3363350', 116),
 ('Tr_3380277', 116),
 ('Tr_3381579', 116),
 ('Tr_3400104', 116),
 ('Tr_3402447', 116),
 ('Tr_3434820', 116),
 ('Tr_3434825', 116),
 ('Tr_3478514', 116),
 ('Tr_3558729', 116),
 ('Tr_3567869', 116),
 ('Tr_3003011', 115),
 ('Tr_3005876', 115),
 ('Tr_3006884', 115),
 ('Tr_3007225', 115),
 ('Tr_3010577', 115),
 ('Tr_3011741', 115),
 ('Tr_3019817', 115),
 ('Tr_3036829', 115),
 ('Tr_3079309', 115),
 ('Tr_3079629', 115),
 ('Tr_3086634', 115),
 ('Tr_3090620', 115),
 ('Tr_3093017', 115),
 ('Tr_3094229', 115),
 ('Tr_3102552', 115),
 ('Tr_3114629', 115),
 ('Tr_3130864', 115),
 ('Tr_3141332', 115),
 ('Tr_3156623', 115),
 ('Tr_3177992', 115),
 ('Tr_3180129', 115),
 ('Tr_3187416', 115),
 ('Tr_3187433', 115),
 ('Tr_3234030', 115),
 ('Tr_3234769', 115),
 ('Tr_3240568', 115),
 ('Tr_3242224', 115),
 ('Tr_3246899', 115),
 ('Tr_3278566', 115),
 ('Tr_3284565', 115),
 ('Tr_3286037', 115),
 ('Tr_3286061', 115),
 ('Tr_3289431', 115),
 ('Tr_3296191', 115),
 ('Tr_3296199', 115),
 ('Tr_3373468', 115),
 ('Tr_3380279', 115),
 ('Tr_3381116', 115),
 ('Tr_3381576', 115),
 ('Tr_3381585', 115),
 ('Tr_3400653', 115),
 ('Tr_3401383', 115),
 ('Tr_3417655', 115),
 ('Tr_3434846', 115),
 ('Tr_3438695', 115),
 ('Tr_3443556', 115),
 ('Tr_3446793', 115),
 ('Tr_3459878', 115),
 ('Tr_3486508', 115),
 ('Tr_3488472', 115),
 ('Tr_3502696', 115),
 ('Tr_3549435', 115),
 ('Tr_3549438', 115),
 ('Tr_3550449', 115),
 ('Tr_3555534', 115),
 ('Tr_3556320', 115),
 ('Tr_3567669', 115),
 ('Tr_3012865', 114),
 ('Tr_3027883', 114),
 ('Tr_3033395', 114),
 ('Tr_3367958', 114),
 ('Tr_3391593', 114),
 ('Tr_3037375', 113),
 ('Tr_3056210', 113),
 ('Tr_3056223', 113),
 ('Tr_3056274', 113),
 ('Tr_3269924', 113),
 ('Tr_3481267', 113),
 ('Tr_3010074', 112),
 ('Tr_3010079', 112),
 ('Tr_3010109', 112),
 ('Tr_3042592', 112),
 ('Tr_3094379', 112),
 ('Tr_3370881', 112),
 ('Tr_3041677', 111),
 ('Tr_3078130', 111),
 ('Tr_3180670', 111),
 ('Tr_3368893', 111),
 ('Tr_3424923', 111),
 ('Tr_3432638', 111),
 ('Tr_3446592', 111),
 ('Tr_3020651', 110),
 ('Tr_3026764', 110),
 ('Tr_3042126', 110),
 ('Tr_3180669', 110),
 ('Tr_3180920', 110),
 ('Tr_3180937', 110),
 ('Tr_3203621', 110),
 ('Tr_3319964', 110),
 ('Tr_3368885', 110),
 ('Tr_3368891', 110),
 ('Tr_3368934', 110),
 ('Tr_3387190', 110),
 ('Tr_3387192', 110),
 ('Tr_3574029', 110),
 ('Tr_3011239', 109),
 ('Tr_3480726', 109),
 ('Tr_3346864', 108),
 ('Tr_3387200', 108),
 ('Tr_3526112', 108),
 ('Tr_3027936', 107),
 ('Tr_3030660', 107),
 ('Tr_3034852', 107),
 ('Tr_3041649', 107),
 ('Tr_3042122', 107),
 ('Tr_3387193', 107),
 ('Tr_3387266', 107),
 ('Tr_3433711', 107),
 ('Tr_3020516', 106),
 ('Tr_3033351', 106),
 ('Tr_3034770', 106),
 ('Tr_3042051', 106),
 ('Tr_3043039', 106),
 ('Tr_3226512', 106),
 ('Tr_3339472', 106),
 ('Tr_3003118', 105),
 ('Tr_3014158', 105),
 ('Tr_3015221', 105),
 ('Tr_3019669', 105),
 ('Tr_3020434', 105),
 ('Tr_3020508', 105),
 ('Tr_3034029', 105),
 ('Tr_3367959', 105),
 ('Tr_3468133', 105),
 ('Tr_3018461', 104),
 ('Tr_3088786', 104),
 ('Tr_3088793', 104),
 ('Tr_3102895', 104),
 ('Tr_3250132', 104),
 ('Tr_3261086', 104),
 ('Tr_3381024', 104),
 ('Tr_3410951', 104),
 ('Tr_3006839', 103),
 ('Tr_3034827', 103),
 ('Tr_3058871', 103),
 ('Tr_3061683', 103),
 ('Tr_3097445', 103),
 ('Tr_3383015', 103),
 ('Tr_3383017', 103),
 ('Tr_3465327', 103),
 ('Tr_3014963', 102),
 ('Tr_3024990', 102),
 ('Tr_3038201', 102),
 ('Tr_3051577', 102),
 ('Tr_3102200', 102),
 ('Tr_3107798', 102),
 ('Tr_3119989', 102),
 ('Tr_3125069', 102),
 ('Tr_3259482', 102),
 ('Tr_3265191', 102),
 ('Tr_3276219', 102),
 ('Tr_3285197', 102),
 ('Tr_3292567', 102),
 ('Tr_3293862', 102),
 ('Tr_3298269', 102),
 ('Tr_3312255', 102),
 ('Tr_3317465', 102),
 ('Tr_3327208', 102),
 ('Tr_3339816', 102),
 ('Tr_3375206', 102),
 ('Tr_3375215', 102),
 ('Tr_3375296', 102),
 ('Tr_3404309', 102),
 ('Tr_3431697', 102),
 ('Tr_3431763', 102),
 ('Tr_3436950', 102),
 ('Tr_3466706', 102),
 ('Tr_3467912', 102),
 ('Tr_3482197', 102),
 ('Tr_3490339', 102),
 ('Tr_3491499', 102),
 ('Tr_3528101', 102),
 ('Tr_3542478', 102),
 ('Tr_3547634', 102),
 ('Tr_3559907', 102),
 ('Tr_3572008', 102),
 ('Tr_3011274', 101),
 ('Tr_3023202', 101),
 ('Tr_3056345', 101),
 ('Tr_3094829', 101),
 ('Tr_3100295', 101),
 ('Tr_3103523', 101),
 ('Tr_3124475', 101),
 ('Tr_3147425', 101),
 ('Tr_3148560', 101),
 ('Tr_3183189', 101),
 ('Tr_3194172', 101),
 ('Tr_3206363', 101),
 ('Tr_3244090', 101),
 ('Tr_3250146', 101),
 ('Tr_3317008', 101),
 ('Tr_3370561', 101),
 ('Tr_3375084', 101),
 ('Tr_3375105', 101),
 ('Tr_3375258', 101),
 ('Tr_3375522', 101),
 ('Tr_3375866', 101),
 ('Tr_3380804', 101),
 ('Tr_3441598', 101),
 ('Tr_3519691', 101),
 ('Tr_3554408', 101),
 ('Tr_2994079', 100),
 ('Tr_2996145', 100),
 ('Tr_3004356', 100),
 ('Tr_3007359', 100),
 ('Tr_3007790', 100),
 ('Tr_3009548', 100),
 ('Tr_3011000', 100),
 ('Tr_3011632', 100),
 ('Tr_3027328', 100),
 ('Tr_3028008', 100),
 ('Tr_3030641', 100),
 ('Tr_3031909', 100),
 ('Tr_3031939', 100),
 ('Tr_3032076', 100),
 ('Tr_3036424', 100),
 ('Tr_3037119', 100),
 ('Tr_3038875', 100),
 ('Tr_3039128', 100),
 ('Tr_3042757', 100),
 ('Tr_3048660', 100),
 ('Tr_3049210', 100),
 ('Tr_3052324', 100),
 ('Tr_3056960', 100),
 ('Tr_3058305', 100),
 ('Tr_3058337', 100),
 ('Tr_3059036', 100),
 ('Tr_3059223', 100),
 ('Tr_3061370', 100),
 ('Tr_3063566', 100),
 ('Tr_3067588', 100),
 ('Tr_3070136', 100),
 ('Tr_3071015', 100),
 ('Tr_3071889', 100),
 ('Tr_3073473', 100),
 ('Tr_3080691', 100),
 ('Tr_3082476', 100),
 ('Tr_3082935', 100),
 ('Tr_3083003', 100),
 ('Tr_3083205', 100),
 ('Tr_3083632', 100),
 ('Tr_3084457', 100),
 ('Tr_3088506', 100),
 ('Tr_3089629', 100),
 ('Tr_3090722', 100),
 ('Tr_3094701', 100),
 ('Tr_3100607', 100),
 ('Tr_3101060', 100),
 ('Tr_3106094', 100),
 ('Tr_3107167', 100),
 ('Tr_3108665', 100),
 ('Tr_3113847', 100),
 ('Tr_3114968', 100),
 ('Tr_3119954', 100),
 ('Tr_3120826', 100),
 ('Tr_3120853', 100),
 ('Tr_3122364', 100),
 ('Tr_3124604', 100),
 ('Tr_3125078', 100),
 ('Tr_3129437', 100),
 ('Tr_3129444', 100),
 ('Tr_3152651', 100),
 ('Tr_3171898', 100),
 ('Tr_3179460', 100),
 ('Tr_3182427', 100),
 ('Tr_3185424', 100),
 ('Tr_3188676', 100),
 ('Tr_3189204', 100),
 ('Tr_3189303', 100),
 ('Tr_3192518', 100),
 ('Tr_3202607', 100),
 ('Tr_3202617', 100),
 ('Tr_3202691', 100),
 ('Tr_3203614', 100),
 ('Tr_3206287', 100),
 ('Tr_3207283', 100),
 ('Tr_3208233', 100),
 ('Tr_3214557', 100),
 ('Tr_3218302', 100),
 ('Tr_3219085', 100),
 ('Tr_3220332', 100),
 ('Tr_3223546', 100),
 ('Tr_3223737', 100),
 ('Tr_3224291', 100),
 ('Tr_3226253', 100),
 ('Tr_3226844', 100),
 ('Tr_3226859', 100),
 ('Tr_3226879', 100),
 ('Tr_3226962', 100),
 ('Tr_3228747', 100),
 ('Tr_3231877', 100),
 ('Tr_3233215', 100),
 ('Tr_3233233', 100),
 ('Tr_3233250', 100),
 ('Tr_3233361', 100),
 ('Tr_3244117', 100),
 ('Tr_3259063', 100),
 ('Tr_3262618', 100),
 ('Tr_3264413', 100),
 ('Tr_3266739', 100),
 ('Tr_3267541', 100),
 ('Tr_3267683', 100),
 ('Tr_3267708', 100),
 ('Tr_3269464', 100),
 ('Tr_3269674', 100),
 ('Tr_3274680', 100),
 ('Tr_3275121', 100),
 ('Tr_3277967', 100),
 ('Tr_3277989', 100),
 ('Tr_3280758', 100),
 ('Tr_3280769', 100),
 ('Tr_3280795', 100),
 ('Tr_3290280', 100),
 ('Tr_3292986', 100),
 ('Tr_3304770', 100),
 ('Tr_3305950', 100),
 ('Tr_3306449', 100),
 ('Tr_3306959', 100),
 ('Tr_3307079', 100),
 ('Tr_3308162', 100),
 ('Tr_3312308', 100),
 ('Tr_3317593', 100),
 ('Tr_3317608', 100),
 ('Tr_3317634', 100),
 ('Tr_3321930', 100),
 ('Tr_3323383', 100),
 ('Tr_3324542', 100),
 ('Tr_3325419', 100),
 ('Tr_3329630', 100),
 ('Tr_3331437', 100),
 ('Tr_3331440', 100),
 ('Tr_3331447', 100),
 ('Tr_3331461', 100),
 ('Tr_3332659', 100),
 ('Tr_3339000', 100),
 ('Tr_3349888', 100),
 ('Tr_3352920', 100),
 ('Tr_3358136', 100),
 ('Tr_3358139', 100),
 ('Tr_3359550', 100),
 ('Tr_3360963', 100),
 ('Tr_3364806', 100),
 ('Tr_3366799', 100),
 ('Tr_3367302', 100),
 ('Tr_3370368', 100),
 ('Tr_3370563', 100),
 ('Tr_3374631', 100),
 ('Tr_3380236', 100),
 ('Tr_3389810', 100),
 ('Tr_3396252', 100),
 ('Tr_3396516', 100),
 ('Tr_3402844', 100),
 ('Tr_3407460', 100),
 ('Tr_3413984', 100),
 ('Tr_3416471', 100),
 ('Tr_3418352', 100),
 ('Tr_3419862', 100),
 ('Tr_3420900', 100),
 ('Tr_3420970', 100),
 ('Tr_3423993', 100),
 ('Tr_3424019', 100),
 ('Tr_3424036', 100),
 ('Tr_3434540', 100),
 ('Tr_3436122', 100),
 ('Tr_3441618', 100),
 ('Tr_3450455', 100),
 ('Tr_3461985', 100),
 ('Tr_3466002', 100),
 ('Tr_3467704', 100),
 ('Tr_3494639', 100),
 ('Tr_3510200', 100),
 ('Tr_3519086', 100),
 ('Tr_3521053', 100),
 ('Tr_3523032', 100),
 ('Tr_3524790', 100),
 ('Tr_3530918', 100),
 ('Tr_3532156', 100),
 ('Tr_3539486', 100),
 ('Tr_3542787', 100),
 ('Tr_3545641', 100),
 ('Tr_3549181', 100),
 ('Tr_3551429', 100),
 ('Tr_3552429', 100),
 ('Tr_3555998', 100),
 ('Tr_3562368', 100),
 ('Tr_3574156', 100),
 ('Tr_2991540', 99),
 ('Tr_2991593', 99),
 ('Tr_2991629', 99),
 ('Tr_2991733', 99),
 ('Tr_2992155', 99),
 ('Tr_2995161', 99),
 ('Tr_2996034', 99),
 ('Tr_3001104', 99),
 ('Tr_3001107', 99),
 ('Tr_3001180', 99),
 ('Tr_3001782', 99),
 ('Tr_3002551', 99),
 ('Tr_3002580', 99),
 ('Tr_3003374', 99),
 ('Tr_3003687', 99),
 ('Tr_3005325', 99),
 ('Tr_3005588', 99),
 ('Tr_3007429', 99),
 ('Tr_3009742', 99),
 ('Tr_3009920', 99),
 ('Tr_3009924', 99),
 ('Tr_3009956', 99),
 ('Tr_3010066', 99),
 ('Tr_3012769', 99),
 ('Tr_3012848', 99),
 ('Tr_3013046', 99),
 ('Tr_3013598', 99),
 ('Tr_3014147', 99),
 ('Tr_3015335', 99),
 ('Tr_3016453', 99),
 ('Tr_3016473', 99),
 ('Tr_3017592', 99),
 ('Tr_3017601', 99),
 ('Tr_3018034', 99),
 ('Tr_3018407', 99),
 ('Tr_3019564', 99),
 ('Tr_3022002', 99),
 ('Tr_3022200', 99),
 ('Tr_3022293', 99),
 ('Tr_3022379', 99),
 ('Tr_3022458', 99),
 ('Tr_3022941', 99),
 ('Tr_3023913', 99),
 ('Tr_3023918', 99),
 ('Tr_3024421', 99),
 ('Tr_3024989', 99),
 ('Tr_3027755', 99),
 ('Tr_3028714', 99),
 ('Tr_3028870', 99),
 ('Tr_3030652', 99),
 ('Tr_3032249', 99),
 ('Tr_3032813', 99),
 ('Tr_3034480', 99),
 ('Tr_3035217', 99),
 ('Tr_3035237', 99),
 ('Tr_3035673', 99),
 ('Tr_3036821', 99),
 ('Tr_3037936', 99),
 ('Tr_3038541', 99),
 ('Tr_3038764', 99),
 ('Tr_3040126', 99),
 ('Tr_3043690', 99),
 ('Tr_3045088', 99),
 ('Tr_3045975', 99),
 ('Tr_3046694', 99),
 ('Tr_3047539', 99),
 ('Tr_3048566', 99),
 ('Tr_3048633', 99),
 ('Tr_3048671', 99),
 ('Tr_3049403', 99),
 ('Tr_3050817', 99),
 ('Tr_3051433', 99),
 ('Tr_3054932', 99),
 ('Tr_3055334', 99),
 ('Tr_3056601', 99),
 ('Tr_3057705', 99),
 ('Tr_3058983', 99),
 ('Tr_3060035', 99),
 ('Tr_3060094', 99),
 ('Tr_3062831', 99),
 ('Tr_3063619', 99),
 ('Tr_3065758', 99),
 ('Tr_3068487', 99),
 ('Tr_3068835', 99),
 ('Tr_3071037', 99),
 ('Tr_3073360', 99),
 ('Tr_3074733', 99),
 ('Tr_3075477', 99),
 ('Tr_3077906', 99),
 ('Tr_3079432', 99),
 ('Tr_3079959', 99),
 ('Tr_3081847', 99),
 ('Tr_3082562', 99),
 ('Tr_3083954', 99),
 ('Tr_3084052', 99),
 ('Tr_3088309', 99),
 ('Tr_3088460', 99),
 ('Tr_3089808', 99),
 ('Tr_3090431', 99),
 ('Tr_3091081', 99),
 ('Tr_3091151', 99),
 ('Tr_3091360', 99),
 ('Tr_3091405', 99),
 ('Tr_3092200', 99),
 ('Tr_3094049', 99),
 ('Tr_3094398', 99),
 ('Tr_3095136', 99),
 ('Tr_3095800', 99),
 ('Tr_3096594', 99),
 ('Tr_3097325', 99),
 ('Tr_3097333', 99),
 ('Tr_3098350', 99),
 ('Tr_3098697', 99),
 ('Tr_3098710', 99),
 ('Tr_3099334', 99),
 ('Tr_3100282', 99),
 ('Tr_3101055', 99),
 ('Tr_3102126', 99),
 ('Tr_3102600', 99),
 ('Tr_3103050', 99),
 ('Tr_3103092', 99),
 ('Tr_3103698', 99),
 ('Tr_3104094', 99),
 ('Tr_3104290', 99),
 ('Tr_3104503', 99),
 ('Tr_3105347', 99),
 ('Tr_3105708', 99),
 ('Tr_3106318', 99),
 ('Tr_3107169', 99),
 ('Tr_3107302', 99),
 ('Tr_3108057', 99),
 ('Tr_3108169', 99),
 ('Tr_3108491', 99),
 ('Tr_3108930', 99),
 ('Tr_3108972', 99),
 ('Tr_3109526', 99),
 ('Tr_3110631', 99),
 ('Tr_3111412', 99),
 ('Tr_3112386', 99),
 ('Tr_3115710', 99),
 ('Tr_3119520', 99),
 ('Tr_3121141', 99),
 ('Tr_3122650', 99),
 ('Tr_3125048', 99),
 ('Tr_3125250', 99),
 ('Tr_3127618', 99),
 ('Tr_3129570', 99),
 ('Tr_3129875', 99),
 ('Tr_3130704', 99),
 ('Tr_3131101', 99),
 ('Tr_3132309', 99),
 ('Tr_3133730', 99),
 ('Tr_3134821', 99),
 ('Tr_3134901', 99),
 ('Tr_3135177', 99),
 ('Tr_3135745', 99),
 ('Tr_3136285', 99),
 ('Tr_3136826', 99),
 ('Tr_3137961', 99),
 ('Tr_3138129', 99),
 ('Tr_3138455', 99),
 ('Tr_3138479', 99),
 ('Tr_3139467', 99),
 ('Tr_3139469', 99),
 ('Tr_3140586', 99),
 ('Tr_3141551', 99),
 ('Tr_3142971', 99),
 ('Tr_3142982', 99),
 ('Tr_3143349', 99),
 ('Tr_3144661', 99),
 ('Tr_3145055', 99),
 ('Tr_3146113', 99),
 ('Tr_3146136', 99),
 ('Tr_3146212', 99),
 ('Tr_3146512', 99),
 ('Tr_3146915', 99),
 ('Tr_3146931', 99),
 ('Tr_3147000', 99),
 ('Tr_3147455', 99),
 ('Tr_3147470', 99),
 ('Tr_3147782', 99),
 ('Tr_3148503', 99),
 ('Tr_3148651', 99),
 ('Tr_3148673', 99),
 ('Tr_3149506', 99),
 ('Tr_3149699', 99),
 ('Tr_3150221', 99),
 ('Tr_3150828', 99),
 ('Tr_3151493', 99),
 ('Tr_3151499', 99),
 ('Tr_3152861', 99),
 ('Tr_3153525', 99),
 ('Tr_3154237', 99),
 ('Tr_3154250', 99),
 ('Tr_3154397', 99),
 ('Tr_3154403', 99),
 ('Tr_3154535', 99),
 ('Tr_3154787', 99),
 ('Tr_3155589', 99),
 ('Tr_3155605', 99),
 ('Tr_3157022', 99),
 ('Tr_3157335', 99),
 ('Tr_3158708', 99),
 ('Tr_3160452', 99),
 ('Tr_3160656', 99),
 ('Tr_3163273', 99),
 ('Tr_3163285', 99),
 ('Tr_3163764', 99),
 ('Tr_3165012', 99),
 ('Tr_3165097', 99),
 ('Tr_3165657', 99),
 ('Tr_3166277', 99),
 ('Tr_3166394', 99),
 ('Tr_3167001', 99),
 ('Tr_3168941', 99),
 ('Tr_3170371', 99),
 ('Tr_3170665', 99),
 ('Tr_3170909', 99),
 ('Tr_3171188', 99),
 ('Tr_3171818', 99),
 ('Tr_3171825', 99),
 ('Tr_3171905', 99),
 ('Tr_3173975', 99),
 ('Tr_3174893', 99),
 ('Tr_3174904', 99),
 ('Tr_3174927', 99),
 ('Tr_3175038', 99),
 ('Tr_3175287', 99),
 ('Tr_3175443', 99),
 ('Tr_3177334', 99),
 ('Tr_3177462', 99),
 ('Tr_3178455', 99),
 ('Tr_3178623', 99),
 ('Tr_3179034', 99),
 ('Tr_3179976', 99),
 ('Tr_3180322', 99),
 ('Tr_3181148', 99),
 ('Tr_3181181', 99),
 ('Tr_3181391', 99),
 ('Tr_3181556', 99),
 ('Tr_3182720', 99),
 ('Tr_3183917', 99),
 ('Tr_3183923', 99),
 ('Tr_3184096', 99),
 ('Tr_3184102', 99),
 ('Tr_3185089', 99),
 ('Tr_3185512', 99),
 ('Tr_3186631', 99),
 ('Tr_3186641', 99),
 ('Tr_3186788', 99),
 ('Tr_3186796', 99),
 ('Tr_3186859', 99),
 ('Tr_3188234', 99),
 ('Tr_3188268', 99),
 ('Tr_3189182', 99),
 ('Tr_3190540', 99),
 ('Tr_3192501', 99),
 ('Tr_3192503', 99),
 ('Tr_3193167', 99),
 ('Tr_3193190', 99),
 ('Tr_3193838', 99),
 ('Tr_3193846', 99),
 ('Tr_3194304', 99),
 ('Tr_3194317', 99),
 ('Tr_3195159', 99),
 ('Tr_3195280', 99),
 ('Tr_3195736', 99),
 ('Tr_3195755', 99),
 ('Tr_3196726', 99),
 ('Tr_3197218', 99),
 ('Tr_3197691', 99),
 ('Tr_3198535', 99),
 ('Tr_3198781', 99),
 ('Tr_3199737', 99),
 ('Tr_3200357', 99),
 ('Tr_3200362', 99),
 ('Tr_3200669', 99),
 ('Tr_3200749', 99),
 ('Tr_3200759', 99),
 ('Tr_3201273', 99),
 ('Tr_3201721', 99),
 ('Tr_3202013', 99),
 ('Tr_3202443', 99),
 ('Tr_3202704', 99),
 ('Tr_3203114', 99),
 ('Tr_3203816', 99),
 ('Tr_3203828', 99),
 ('Tr_3204832', 99),
 ('Tr_3204928', 99),
 ('Tr_3205535', 99),
 ('Tr_3206173', 99),
 ('Tr_3206264', 99),
 ('Tr_3208999', 99),
 ('Tr_3209006', 99),
 ('Tr_3209316', 99),
 ('Tr_3210033', 99),
 ('Tr_3210403', 99),
 ('Tr_3210925', 99),
 ('Tr_3211697', 99),
 ('Tr_3214286', 99),
 ('Tr_3214806', 99),
 ('Tr_3215787', 99),
 ('Tr_3217443', 99),
 ('Tr_3217455', 99),
 ('Tr_3217472', 99),
 ('Tr_3219314', 99),
 ('Tr_3220497', 99),
 ('Tr_3220576', 99),
 ('Tr_3221007', 99),
 ('Tr_3222295', 99),
 ('Tr_3222470', 99),
 ('Tr_3225537', 99),
 ('Tr_3226377', 99),
 ('Tr_3228669', 99),
 ('Tr_3228746', 99),
 ('Tr_3228757', 99),
 ('Tr_3228845', 99),
 ('Tr_3229294', 99),
 ('Tr_3229324', 99),
 ('Tr_3229360', 99),
 ('Tr_3229363', 99),
 ('Tr_3230502', 99),
 ('Tr_3232137', 99),
 ('Tr_3233564', 99),
 ('Tr_3233695', 99),
 ('Tr_3234062', 99),
 ('Tr_3234785', 99),
 ('Tr_3235176', 99),
 ('Tr_3235199', 99),
 ('Tr_3235658', 99),
 ('Tr_3236030', 99),
 ('Tr_3236147', 99),
 ('Tr_3236150', 99),
 ('Tr_3236926', 99),
 ('Tr_3237454', 99),
 ('Tr_3239115', 99),
 ('Tr_3239236', 99),
 ('Tr_3241412', 99),
 ('Tr_3241416', 99),
 ('Tr_3241533', 99),

In [198]:
# adding in fraudulent tranasctions so that it is also included in the graph

fraud_mappings = {
    f'Tr_{trans_id}': fraud_status
    for trans_id, fraud_status in zip(
        train_transaction.TransactionID,
        train_transaction.isFraud
    )
}

# setting fraud values on the graph transaction nodes
nx.set_node_attributes(trans_to_trans_graph, fraud_mappings, 'fraud_status')

In [244]:
# will explore the fraud ratios on the top 15 most connected nodes
nodes_of_interest = sorted(list(trans_to_trans_graph.degree()), key=lambda x: x[1], reverse=True)[:15]

In [250]:
# looking at the neighbors of the most connected transaction
# neighbors = trans_to_trans_graph.neighbors('Tr_2987288')
node_of_interest = 'Tr_2987288'

# keep list of tupeles of (node, fraud_count, neighbors, ratio)
fraud_counts = []

# get fraud counts for all nodes of interest
for node, total_connections in nodes_of_interest:
    # exploring the fraud count of the neighbors of this transaction
    fraud_count = sum(
        trans_to_trans_graph.nodes[n].get('fraud_status', 0)
        for n in trans_to_trans_graph.neighbors(node)  
    )
    
    fraud_counts.append((node, fraud_count, total_connections, (round(fraud_count / total_connections, 4))))

In [251]:
fraud_counts

[('Tr_3231911', 3, 231, 0.013),
 ('Tr_3231907', 3, 230, 0.013),
 ('Tr_3231926', 3, 230, 0.013),
 ('Tr_3021585', 6, 186, 0.0323),
 ('Tr_3021643', 6, 186, 0.0323),
 ('Tr_3023706', 6, 186, 0.0323),
 ('Tr_3010766', 6, 183, 0.0328),
 ('Tr_3031080', 0, 182, 0.0),
 ('Tr_3031088', 0, 182, 0.0),
 ('Tr_3014200', 6, 178, 0.0337),
 ('Tr_3015164', 6, 178, 0.0337),
 ('Tr_3347905', 6, 178, 0.0337),
 ('Tr_3011956', 7, 176, 0.0398),
 ('Tr_3057921', 7, 176, 0.0398),
 ('Tr_3169705', 7, 176, 0.0398)]

### Feature creation next
- degree
- weighted_degree
- component_size
- neighbor_fraud_ratio
- average_neighbor_degree
- average_edge_weight
- clustering_coefficient
- pagerank

In [253]:
# degree
t2t_degree_dict = dict(trans_to_trans_graph.degree())

# weighted degrees
t2t_w_degree_dict = dict(trans_to_trans_graph.degree(weight='weight'))

# clustering coef.: looks at how connected interconnected neighbors are to a given node
t2t_clustering_coef_dict = nx.clustering(trans_to_trans_graph, weight='weight')

# page rank: details how influential a node is on it neighborhood
t2t_page_rank_dict = nx.pagerank(trans_to_trans_graph, weight='weight')

In [257]:
nx.to_scipy_sparse_array(trans_to_trans_graph)

<Compressed Sparse Row sparse array of dtype 'int64'
	with 4912860 stored elements and shape (590540, 590540)>

In [ ]:
# manually implemented graph features

# connected component size
comp_sizes = {}
for comp in nx.connected_components(trans_to_trans_graph):
    size = len(comp)
    for node in comp:
        comp_sizes[node] = size

# neighbor fraud ratio
# this needs to be done by turning the edges dict in to a dataframe and then merging the lable info onto it from train_transaction
# # edges = pd.DataFrame(G.edges(), columns=['src', 'dst'])
# this is also undirected so dont forget to add al revers realtions too before calculating ratios
# edges_rev = edges.rename(
#     columns={'src':'dst', 'dst':'src'}
# )

# edges_full = pd.concat([edges, edges_rev])

# average edge weight
# this will be easier to calculate directly on the df since it is just (weighted degree / degree)