## Data descriptions

---
In this competition you are predicting the probability that an online transaction is fraudulent, as denoted by the binary target isFraud.

The data is broken into two files identity and transaction, which are joined by TransactionID. Not all transactions have corresponding identity information.

Categorical Features - Transaction
ProductCD
card1 - card6
addr1, addr2
P_emaildomain
R_emaildomain
M1 - M9
Categorical Features - Identity
DeviceType
DeviceInfo
id_12 - id_38
The TransactionDT feature is a timedelta from a given reference datetime (not an actual timestamp).

You can read more about the data from this post by the competition host.

Files
train_{transaction, identity}.csv - the training set
test_{transaction, identity}.csv - the test set (you must predict the isFraud value for these observations)
sample_submission.csv - a sample submission file in the correct format

---

I see many questions regarding data description, so it maybe a better idea to open a thread for discussion. The following is a bit more details about it:

Transaction Table *

TransactionDT: timedelta from a given reference datetime (not an actual timestamp)

TransactionAMT: transaction payment amount in USD

ProductCD: product code, the product for each transaction

card1 - card6: payment card information, such as card type, card category, issue bank, country, etc.

addr: address

dist: distance

P_ and (R__) emaildomain: purchaser and recipient email domain

C1-C14: counting, such as how many addresses are found to be associated with the payment card, etc. The actual meaning is masked.

D1-D15: timedelta, such as days between previous transaction, etc.

M1-M9: match, such as names on card and address, etc.

Vxxx: Vesta engineered rich features, including ranking, counting, and other entity relations.

Categorical Features: ProductCD card1 - card6 addr1, addr2 P_emaildomain R_emaildomain M1 - M9

Identity Table *

Variables in this table are identity information – network connection information (IP, ISP, Proxy, etc) and digital signature (UA/browser/os/version, etc) associated with transactions. They're collected by Vesta’s fraud protection system and digital security partners. (The field names are masked and pairwise dictionary will not be provided for privacy protection and contract agreement)

Categorical Features: DeviceType DeviceInfo id_12 - id_38

---

In [13]:
import pandas as pd
import networkx as nx

In [14]:
train_identity = pd.read_csv('ieee-fraud-detection/train_identity.csv')
train_transaction = pd.read_csv('ieee-fraud-detection/train_transaction.csv')

In [15]:
train_identity.head()

,TransactionID,id_01,id_02,id_03,id_04,id_05,id_06,id_07,id_08,id_09,...,id_31,id_32,id_33,id_34,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo
0,2987004,0.0,70787.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,samsung browser 6.2,32.0,2220x1080,match_status:2,T,F,T,T,mobile,SAMSUNG SM-G892A Build/NRD90M
1,2987008,-5.0,98945.0,NaN,NaN,0.0,-5.0,NaN,NaN,NaN,...,mobile safari 11.0,32.0,1334x750,match_status:1,T,F,F,T,mobile,iOS Device
2,2987010,-5.0,191631.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,Windows
3,2987011,-5.0,221832.0,NaN,NaN,0.0,-6.0,NaN,NaN,NaN,...,chrome 62.0,NaN,NaN,NaN,F,F,T,T,desktop,NaN
4,2987016,0.0,7460.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,...,chrome 62.0,24.0,1280x800,match_status:2,T,F,T,T,desktop,MacOS

In [16]:
train_transaction.head().iloc[:, :12]

,TransactionID,isFraud,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1
0,2987000,0,86400,68.5,W,13926,NaN,150.0,discover,142.0,credit,315.0
1,2987001,0,86401,29.0,W,2755,404.0,150.0,mastercard,102.0,credit,325.0
2,2987002,0,86469,59.0,W,4663,490.0,150.0,visa,166.0,debit,330.0
3,2987003,0,86499,50.0,W,18132,567.0,150.0,mastercard,117.0,debit,476.0
4,2987004,0,86506,50.0,H,4497,514.0,150.0,mastercard,102.0,credit,420.0

# Plan for making a graph
- Many nodes: eamils, transaction id, addresses, devices, IP information (identify all of these in the two data tables and work on relating the in networkx)
- Make all edges connections from transaction to other node types

``` 
Basic example to build from
import networkx as nx

G = nx.Graph()

for _, row in df.iterrows():
    t = f"T_{row['TransactionID']}"
    card = f"C_{row['card1']}"
    
    G.add_edge(t, card)
```

In [17]:
train_identity[['id_01', 'id_02']]

        id_01     id_02
0         0.0   70787.0
1        -5.0   98945.0
2        -5.0  191631.0
3        -5.0  221832.0
4         0.0    7460.0
...       ...       ...
144228  -15.0  145955.0
144229   -5.0  172059.0
144230  -20.0  632381.0
144231   -5.0   55528.0
144232  -45.0  339406.0

[144233 rows x 2 columns]

In [32]:
def create_graph_edges_for_similar_cols(
        target_graph: nx.Graph,
        target_df: pd.DataFrame, 
        primary_node_col: str,
        primary_node_prefix: str,
        target_col_names: list[str], 
        ref_node_prefix: str, 
        ref_node_suffix: list[str] = None
    ) -> int:
    """
        This is a utility function for iterating similar columns that might need to be added to a graph in bulk. It will edit the graph passed in the argument directly.
        Retruns the size of the updated graph.

        graph: An instance of a networkx graph that needs to have connections added to it
        target_df: The data frame containing all reference columns for the mappings
        primary_node_col: The name of the column that will server as the primary node that should as the basis for many connections (ex. Transactions in a case where you want to connect many other attributes about that transaction to it),
        primary_node_prefix: A string that is the prefix for the primary node that will be used on the Graph (ex. if the primary node is Transactions you may want to use something like 'T' or 'Tr')
        target_col_names: a list of strings containing the names of columns in the target DataFrame that need to have relationships created for
        graph_label_prefix: the desired prefix for the target column to be associated with in the graph (ex if the columns are all related to credit card info you may want to use somehting like 'C')
        graph_label_suffix: this is the method for appending unique identifiers to the graph_label_prefix when there are multiple cols (once again for card info you may want something like C1, C2 ...)
                            If nothing is passed to this argument it will fill with 1 - n where n is the len of the  target_col_names. If you want custom functionality pass list of the suffix values in order.
    """
    tdf = target_df.copy() # ensure that the orginal df is not edited by this

    if ref_node_suffix != None:
        assert len(set(ref_node_suffix)) == len(ref_node_suffix), 'Graph label suffix values must be unique.'
    else: 
        ref_node_suffix = list(range(1, len(target_col_names) + 1)) # default functionality for using digits as the suffix

    for col_name, suffix in zip(target_col_names, ref_node_suffix):
        mask = tdf[col_name].notna()
        
        target_data = tdf[mask]

        connection_tuple_mappings = zip(
            f'{primary_node_prefix}_' + target_data[primary_node_col].astype('str'), 
            f'{ref_node_prefix}{suffix}_' + target_data[col_name].astype('str') # puts creates prefix of C1, C2, ... to C6 so each card identifier is unique
        )

        target_graph.add_edges_from(connection_tuple_mappings)
    
    return target_graph.size()

In [33]:
# get all connections created
# zipping the target cols as string and using add_edges_from() is more efficent so use this

# instantiate the graph
transactions_graph = nx.Graph()

# get all relevant fields that need to be added to the graph (all of this centers on transaction IDs and attributes that relate to those)
# all card data (card1 - card6)
card_cols = ['card1', 'card2', 'card3', 'card4', 'card5', 'card6']

# create card connections
create_graph_edges_for_similar_cols(
    target_graph= transactions_graph,
    target_df=train_transaction,
    primary_node_col='TransactionID',
    primary_node_prefix='Tr',
    target_col_names=card_cols,
    ref_node_prefix='C'
)

addr_cols = ['addr1', 'addr2']
# address info (addr1 and addr2 )
create_graph_edges_for_similar_cols(
    target_graph= transactions_graph,
    target_df=train_transaction,
    primary_node_col='TransactionID',
    primary_node_prefix='Tr',
    target_col_names=addr_cols,
    ref_node_prefix='Addr'
)

# identity information is next
# Looks like id_02 is the only thing that can reasonably be used without introducing a bunch of nodes with artificially high degree measures
create_graph_edges_for_similar_cols(
    target_graph= transactions_graph,
    target_df=train_identity,
    primary_node_col='TransactionID',
    primary_node_prefix='Tr',
    target_col_names=['id_02'],
    ref_node_prefix='Id'
)

4715875

In [34]:
# inspecting basic graph attributes
print(f'Number of edges: {transactions_graph.number_of_edges()}')
print(f'Number of ndoes:  {transactions_graph.number_of_nodes()}')

Number of edges: 4715875
Number of ndoes:  720895

In [36]:
from collections import Counter

# looking at the nodes by each column from the original data set
Counter(n.split('_')[0] for n in transactions_graph.nodes)

Counter({'Tr': 590540,
         'Id1': 115655,
         'C1': 13553,
         'C2': 500,
         'Addr1': 332,
         'C5': 119,
         'C3': 114,
         'Addr2': 74,
         'C4': 4,
         'C6': 4})

In [ ]:
# analyzing the degree structure of the nodes

In [39]:
nodes_sorted_by_degree = sorted(list(transactions_graph.degree), key=lambda x: x[1], reverse=True)
nodes_sorted_by_degree[:20]

[('C3_150.0', 521287),
 ('Addr2_87.0', 520481),
 ('C6_debit', 439938),
 ('C4_visa', 384767),
 ('C5_226.0', 296546),
 ('C4_mastercard', 189217),
 ('C6_credit', 148986),
 ('C5_224.0', 81513),
 ('C5_166.0', 57140),
 ('C3_185.0', 56346),
 ('C2_321.0', 48935),
 ('Addr1_299.0', 46335),
 ('C2_111.0', 45191),
 ('Addr1_325.0', 42751),
 ('Addr1_204.0', 42020),
 ('C2_555.0', 41995),
 ('Addr1_264.0', 39870),
 ('C2_490.0', 38145),
 ('C5_102.0', 29105),
 ('Addr1_330.0', 26287)]

- It looks like C4 and C6 values may not be very useful here since they are generic categorical classifications that are likely to be shared and connect too many values.
- Will coninue to explore non-transaction nodes for high connectivity

In [40]:
nodes_to_explore = []

for pair in nodes_sorted_by_degree:
    non_interesting_nodes = ['Tr', 'C4', 'C6']
    node = pair[0]

    if node[:2] in non_interesting_nodes: continue

    nodes_to_explore.append(pair)

In [42]:
nodes_to_explore[:20]

[('C3_150.0', 521287),
 ('Addr2_87.0', 520481),
 ('C5_226.0', 296546),
 ('C5_224.0', 81513),
 ('C5_166.0', 57140),
 ('C3_185.0', 56346),
 ('C2_321.0', 48935),
 ('Addr1_299.0', 46335),
 ('C2_111.0', 45191),
 ('Addr1_325.0', 42751),
 ('Addr1_204.0', 42020),
 ('C2_555.0', 41995),
 ('Addr1_264.0', 39870),
 ('C2_490.0', 38145),
 ('C5_102.0', 29105),
 ('Addr1_330.0', 26287),
 ('C5_117.0', 25941),
 ('Addr1_315.0', 23078),
 ('C2_583.0', 21803),
 ('Addr1_441.0', 20827)]

In [9]:
max(nx.connected_components(transactions_graph), key=len)

{'Tr3027247',
 'Id1506675.0',
 'Tr3517133',
 'Tr3222411',
 'Tr3554750',
 'Tr3485637',
 'Id154755.0',
 'Tr3196319',
 'Tr3526392',
 'Tr3128844',
 'Tr3060474',
 'Tr3459293',
 'Tr3489270',
 'Id123480.0',
 'Tr3380852',
 'Tr3559754',
 'Tr3021120',
 'Tr3009041',
 'Tr3198508',
 'Tr3341075',
 'Tr3142742',
 'Tr3442970',
 'Tr2997350',
 'Tr3128850',
 'Tr2991797',
 'Id1343575.0',
 'Tr3053859',
 'Tr3467576',
 'Tr3483581',
 'Tr3470403',
 'Tr3305281',
 'Tr3306006',
 'Id1152682.0',
 'Tr3008633',
 'Id1166207.0',
 'Tr3110890',
 'Tr3384589',
 'Tr3552607',
 'Tr3100226',
 'Tr3062326',
 'Id1354301.0',
 'Tr3397424',
 'Tr3323546',
 'Tr3539008',
 'Tr3286691',
 'Tr3500605',
 'Tr3047150',
 'Id1152712.0',
 'Tr3388842',
 'Tr3228353',
 'Tr3083395',
 'Tr3210827',
 'Tr3339028',
 'Tr3467320',
 'Tr3060962',
 'Tr3088702',
 'Tr3409400',
 'Tr3566663',
 'Tr3427559',
 'Tr3222891',
 'Id1201745.0',
 'Id1181529.0',
 'Tr3146068',
 'Tr3294013',
 'Id156047.0',
 'Tr3362479',
 'Tr3508736',
 'Tr3055206',
 'Tr3116393',
 'Tr3489402',
 'Tr3162193',
 'Tr3469768',
 'Id1150746.0',
 'Tr3104027',
 'Tr3413559',
 'Tr3520667',
 'Tr3550722',
 'Id190019.0',
 'Tr3154597',
 'Id1124685.0',
 'Tr3135864',
 'Tr3443274',
 'Tr3268656',
 'Id1933931.0',
 'Tr3228819',
 'Tr3244963',
 'Tr3043079',
 'Id1136342.0',
 'Tr3189886',
 'Tr3049018',
 'Id1192770.0',
 'Id1206669.0',
 'Id129923.0',
 'Id1215770.0',
 'Tr3553459',
 'Tr3403577',
 'Tr3249840',
 'Id1144819.0',
 'Tr3537732',
 'Tr3395761',
 'Tr3217082',
 'Tr3148400',
 'Tr3461239',
 'Tr3472287',
 'Tr3021366',
 'Tr3499426',
 'Tr3165745',
 'Tr3560478',
 'Tr3211775',
 'Tr3146916',
 'Tr3029260',
 'Tr3092604',
 'Tr3170272',
 'Tr3248979',
 'Id144004.0',
 'Tr3489302',
 'Id165801.0',
 'Tr3219812',
 'Tr3403408',
 'Tr3538557',
 'Tr3529007',
 'Tr3510586',
 'Tr3209917',
 'Tr3447709',
 'Tr3267493',
 'Tr3091301',
 'Id166976.0',
 'Tr3252907',
 'Tr3448710',
 'Tr3286705',
 'Tr3120626',
 'Tr3394325',
 'Tr3500072',
 'Tr3136541',
 'Tr3197861',
 'Tr3418492',
 'Tr3270072',
 'Tr3001686',
 'Tr3027674',
 'Tr3485808',
 'Tr3300081',
 'Tr3243925',
 'Tr3212105',
 'Tr3254558',
 'Tr3152520',
 'Tr3387117',
 'Tr3008814',
 'Tr3032150',
 'Tr3180270',
 'Tr3102272',
 'Tr3181218',
 'Tr3181926',
 'Tr3432253',
 'Tr3241102',
 'Tr3505765',
 'Tr3479547',
 'Tr3542505',
 'Tr3325135',
 'Tr3566428',
 'Id1238781.0',
 'Tr3384625',
 'Id1342435.0',
 'Tr3212814',
 'Tr3231849',
 'Tr3145079',
 'Id1409961.0',
 'Id1433798.0',
 'Tr3377708',
 'Tr3449187',
 'Tr3354830',
 'Tr3477030',
 'Tr3267068',
 'Tr3568414',
 'Tr3358746',
 'Tr3351438',
 'Tr3025530',
 'Tr3173910',
 'Tr3370962',
 'Tr3451794',
 'Tr3474692',
 'Tr3156654',
 'Tr3409875',
 'Tr2990665',
 'Tr3126605',
 'Tr3091194',
 'Tr3390572',
 'Id1154373.0',
 'Tr3312988',
 'Tr3212416',
 'Tr3018488',
 'Tr3124003',
 'C16008',
 'Tr3365479',
 'Tr3418075',
 'Tr3344875',
 'Tr3202061',
 'Id161292.0',
 'Tr3404459',
 'Tr3427288',
 'Tr3044280',
 'Tr3005048',
 'Tr3271545',
 'Tr3054344',
 'C19988',
 'Tr3010233',
 'Id1135791.0',
 'Tr3139336',
 'Id1264508.0',
 'Tr3067048',
 'Tr3016665',
 'Tr3002114',
 'Tr3498999',
 'Tr3540390',
 'Tr3358644',
 'Tr3479186',
 'Tr3455980',
 'Tr3154153',
 'Tr3534780',
 'Tr3547180',
 'Tr3048811',
 'Tr3441325',
 'Tr3131102',
 'Tr3454430',
 'Tr3221658',
 'Tr3462598',
 'Tr3061998',
 'Tr3109371',
 'Tr3406382',
 'Tr3205098',
 'Tr3157647',
 'Tr3276479',
 'Tr3254465',
 'Tr3482710',
 'Tr3017550',
 'Tr3197923',
 'C116566',
 'Tr3112428',
 'Tr3235583',
 'Tr3435345',
 'Tr3256699',
 'Tr3190706',
 'Tr3086417',
 'Tr3558474',
 'Tr3556294',
 'Tr3362208',
 'Id12115.0',
 'Tr3344868',
 'Tr3417111',
 'Tr2992819',
 'Tr2992291',
 'Tr3400759',
 'Id1361277.0',
 'Tr3239978',
 'Id1168782.0',
 'Tr3087694',
 'Tr3495247',
 'Tr3224401',
 'Tr3236902',
 'Id1117906.0',
 'Tr3561933',
 'Tr3380022',
 'Tr3338318',
 'Tr3166523',
 'Tr3575310',
 'Tr3569901',
 'Tr3428574',
 'Tr3166644',
 'Tr3474948',
 'Tr3373885',
 'Tr3226483',
 'Tr3536117',
 'Tr3294272',
 'Tr3049027',
 'Tr3049734',
 'Tr3050226',
 'Id179221.0',
 'Tr3416266',
 'Tr3438181',
 'Tr3081200',
 'Tr3297735',
 'Tr3048942',
 'Tr3469629',
 'Tr3056288',
 'Tr3475640',
 'Tr3090728',
 'Tr3141905',
 'Tr3228984',
 'Tr3015908',
 'Tr3539881',
 'Tr3533141',
 'Tr3515011',
 'Tr3028932',
 'Tr2993354',
 'Tr3420930',
 'Id1266382.0',
 'Tr3458088',
 'Tr3229314',
 'Tr3147504',
 'Tr3490008',
 'Id1297.0',
 'Tr3557656',
 'Tr3496173',
 'Tr3104423',
 'Tr3549563',
 'Id1102947.0',
 'Tr3354353',
 'Id179664.0',
 'Tr3230891',
 'Tr3544709',
 'Id1305564.0',
 'Tr3124844',
 'C14040',
 'Tr3463192',
 'Tr3320250',
 'Tr3005248',
 'Tr3033450',
 'Tr3403855',
 'Tr3117464',
 'Tr3498533',
 'Tr3267764',
 'C112647',
 'Tr3202835',
 'Tr3195435',
 'Tr3385352',
 'Tr3355717',
 'Tr3092785',
 'Tr3320387',
 'Tr3128609',
 'Tr3245646',
 'Tr2992337',
 'Tr3450992',
 'Tr2989338',
 'Id1407920.0',
 'Tr3153799',
 'C18553',
 'Tr3518311',
 'Tr3041896',
 'Tr3485280',
 'Tr3098606',
 'Tr3374575',
 'C112291',
 'Tr3422992',
 'Tr3498374',
 'Tr2990398',
 'Tr3139008',
 'Tr3325540',
 'Tr3498954',
 'Tr3045182',
 'Tr3122847',
 'Tr3141028',
 'Id1144889.0',
 'Tr3269392',
 'Tr3405221',
 'Tr3043044',
 'Id1621980.0',
 'Id1250264.0',
 'Tr3325922',
 'Tr3424571',
 'Tr3414302',
 'Tr3421214',
 'Tr3152490',
 'Tr3249635',
 'Id1144251.0',
 'Tr3147812',
 'Id176980.0',
 'Tr3349795',
 'Tr3147315',
 'Tr3215501',
 'Tr3481900',
 'Tr3516757',
 'Tr3021083',
 'Tr3315012',
 'Tr3406657',
 'Id1127192.0',
 'Tr3112722',
 'Tr3212684',
 'Id171686.0',
 'Tr3375477',
 'Id1108023.0',
 'Tr3377652',
 'Tr3295043',
 'Tr3232625',
 'Id1275977.0',
 'Tr3189943',
 'Id1141164.0',
 'Id162098.0',
 'Tr3523855',
 'Tr3154822',
 'Id17458.0',
 'Tr3565929',
 'Id187845.0',
 'Tr3561319',
 'Tr3124440',
 'Tr3253381',
 'Tr3494890',
 'Tr3156588',
 'Tr3056364',
 'Tr3171793',
 'Id1108567.0',
 'Id166719.0',
 'Tr3184302',
 'Tr3262564',
 'Tr3471483',
 'Tr3564991',
 'Tr3164534',
 'Tr3203587',
 'C113173',
 'Tr3508615',
 'Tr3043761',
 'Tr3301485',
 'Id1209444.0',
 'Tr3419355',
 'Tr3200382',
 'Tr3268799',
 'Tr3448805',
 'Tr3310352',
 'Id11280.0',
 'Tr3406606',
 'C16990',
 'Tr3299971',
 'Tr3201348',
 'Tr3256999',
 'Tr3561796',
 'Tr3320629',
 'Tr3510423',
 'Tr3002254',
 'Tr3536947',
 'Tr3477232',
 'Tr3483716',
 'Tr2995887',
 'Tr3229298',
 'Tr3495978',
 'Tr3337452',
 'Tr3148737',
 'Tr3569141',
 'Id15633.0',
 'Tr3095499',
 'Tr3051513',
 'Tr3479533',
 'Tr3524614',
 'Id1669507.0',
 'Id159167.0',
 'C16400',
 'Id1733630.0',
 'Tr3378570',
 'Id1343501.0',
 'Tr3502945',
 'Tr3134853',
 'Tr3115330',
 'Id1128792.0',
 'Tr3353045',
 'Tr3260280',
 'Tr3555106',
 'Tr3301871',
 'Tr3431567',
 'Tr3308224',
 'Tr3188838',
 'Id163547.0',
 'Tr3393982',
 'Tr3329357',
 'Tr3299534',
 'Tr3357276',
 'Tr3532854',
 'Tr3539335',
 'Id189917.0',
 'Tr3219701',
 'Tr3029245',
 'Tr3057675',
 'Tr3286521',
 'Tr3146021',
 'Tr3446282',
 'C18326',
 'Tr3047553',
 'Tr3394212',
 'Id1100335.0',
 'Tr3496853',
 'Tr3412407',
 'Tr3337580',
 'Tr3061505',
 'Tr3408594',
 'Tr3091287',
 'Tr3183924',
 'Id145398.0',
 'Tr3425557',
 'Tr3323408',
 'Tr3141870',
 'Tr3096035',
 'Tr3510460',
 'Tr3408637',
 'Tr3018704',
 'Tr3319280',
 'Tr3495243',
 'Tr3234266',
 'Tr3479326',
 'Tr3284515',
 'Tr3143614',
 'Tr3313584',
 'Tr3159755',
 'Tr3481369',
 'Tr3028908',
 'Tr3334387',
 'Tr3314251',
 'Tr3437454',
 'Tr3113183',
 'Id16907.0',
 'Tr3117913',
 'Id1589866.0',
 'Tr3020570',
 'Tr3416170',
 'Tr3438109',
 'Id170967.0',
 'Tr3436447',
 'Tr3066700',
 'Tr3211141',
 'Tr3118923',
 'Tr3125691',
 'Tr3258109',
 'Tr3072072',
 'Id1430410.0',
 'Tr3008417',
 'Tr3273825',
 'Tr3063469',
 'Tr3131455',
 'Tr3352767',
 'Tr3184377',
 'Tr3572296',
 'Tr3439066',
 'Tr3448586',
 'Id162941.0',
 'Id1176566.0',
 'Tr3180262',
 'Tr3418643',
 'Tr3253571',
 'Tr3268227',
 'Tr2994747',
 'Tr3318593',
 'Id196423.0',
 'Tr2997837',
 'Tr3017055',
 'Tr3427455',
 'Tr3284266',
 'Tr3211136',
 'Tr3082199',
 'Tr3024497',
 'Tr3083528',
 'Tr3196274',
 'Tr3404515',
 'Tr3377038',
 'Tr3515389',
 'Tr3219087',
 'Tr3226425',
 'Tr3017367',
 'Tr3380669',
 'Tr3401438',
 'Tr3115247',
 'Tr3292543',
 'Tr3178599',
 'Id1113515.0',
 'Tr3120652',
 'Id177656.0',
 'Tr3256083',
 'Tr3149221',
 'Tr3254421',
 'Tr3467979',
 'Tr3230602',
 'Tr3153548',
 'Tr3402066',
 'Tr3080122',
 'Tr3073837',
 'Tr3195417',
 'Tr3418884',
 'Tr3053683',
 'Id1181831.0',
 'Tr3430304',
 'Tr3567811',
 'Tr3213221',
 'Tr3284115',
 'C114038',
 'Tr3392415',
 'Tr3050868',
 'Id1220542.0',
 'Tr3574892',
 'Id193592.0',
 'Tr3296331',
 'Tr3480798',
 'Tr3201338',
 'Tr3087673',
 'Tr2991787',
 'Tr3236643',
 'Tr3243591',
 'Tr3308032',
 'Tr3464483',
 'Tr3484524',
 'Id162073.0',
 'Id1116797.0',
 'Id168077.0',
 'Tr3455961',
 'Tr3439621',
 'Tr3219544',
 'Tr3025103',
 'Tr3270155',
 'Tr3339614',
 'Tr3413401',
 'Tr3295288',
 'Tr3128970',
 'Tr3224773',
 'Id1111859.0',
 'Tr3056422',
 'Tr3186441',
 'Tr3230997',
 'Tr3170009',
 'Tr3370272',
 'Id174861.0',
 'Tr3033904',
 'Tr3391960',
 'Tr3174960',
 'Tr3223081',
 'Tr3406011',
 'Tr3563475',
 'C116920',
 'Id1391938.0',
 'Id171520.0',
 'Tr3169098',
 'Tr3558962',
 'Id1415437.0',
 'Id140695.0',
 'Tr3438632',
 'Tr3369518',
 'Tr3299347',
 'Tr3138153',
 'Tr3390911',
 'Tr3286317',
 'Tr3313704',
 'Tr3031744',
 'Tr3291237',
 'Tr3303476',
 'Tr3349168',
 'Tr3196600',
 'Tr3075884',
 'Tr3302650',
 'C12792',
 'Tr3525230',
 'Id1611373.0',
 'Tr3310462',
 'Tr3352280',
 'Tr3106492',
 'Tr3309326',
 'Tr3475570',
 'Tr3433388',
 'Tr3190705',
 'Tr3061040',
 'Tr3452002',
 'Tr3505927',
 'Tr3309543',
 'Id1127394.0',
 'Id1178297.0',
 'Tr3183802',
 'Tr2996375',
 'Tr3325992',
 'Id186629.0',
 'Id161238.0',
 'Tr3554853',
 'Tr3438788',
 'Tr3274797',
 'Tr3450121',
 'Id143698.0',
 'Tr3465129',
 'Tr3065315',
 'Tr3268160',
 'Tr3506214',
 'Tr3076679',
 'Tr3194877',
 'Tr3047609',
 'Id1356229.0',
 'Tr3573749',
 'Tr3409507',
 'Tr3163846',
 'Tr3275160',
 'Tr3195725',
 'Tr3474193',
 'Tr3360197',
 'Tr3178482',
 'Id1111266.0',
 'Tr3543455',
 'Tr3040980',
 'Id1285211.0',
 'Tr3094211',
 'Tr3208720',
 'Tr3126100',
 'Tr3539856',
 'Tr2990282',
 'Tr3150163',
 'Id1141876.0',
 'Id1164428.0',
 'Id1305533.0',
 'Tr3518391',
 'Tr3003528',
 'Tr3074647',
 'Tr3504244',
 'Tr3367136',
 'C13307',
 'Tr3036956',
 'Tr3090054',
 'Tr3481366',
 'Tr3369748',
 'Tr3224468',
 'Tr3329425',
 'Tr2992472',
 'Tr3244870',
 'Tr3292288',
 'Tr3107304',
 'Tr3046711',
 'Tr3335508',
 'Tr3274923',
 'Tr3380051',
 'Tr3127666',
 'Tr3576992',
 'Tr3482460',
 'Tr3269305',
 'Tr3074806',
 'Tr3233218',
 'Id168339.0',
 'Tr3134889',
 'Tr3035915',
 'Tr3281829',
 'Tr3388948',
 'Tr3425438',
 'Tr3224254',
 'Id180721.0',
 'Id1145491.0',
 'Tr3569528',
 'Tr3427127',
 'Tr3508149',
 'Tr3445362',
 'Tr3356510',
 'Tr2987898',
 'Tr3373521',
 'Tr3069460',
 'Tr3092869',
 'Id1349157.0',
 'Id175868.0',
 'Id193909.0',
 'Id147305.0',
 'Tr3343392',
 'Tr3093964',
 'Tr3310125',
 'Id144638.0',
 'Tr3162880',
 'Tr3499175',
 'Id1283976.0',
 'Tr3279126',
 'Tr3356465',
 'Id1107844.0',
 'Id1365637.0',
 'Tr3554698',
 'Id1207763.0',
 'Tr3444053',
 'Tr3162221',
 'Tr3306380',
 'Tr3132637',
 'Id1201412.0',
 'Tr3556577',
 'Tr3158181',
 'Tr3479999',
 'Id1116673.0',
 'Id1248781.0',
 'Id1263645.0',
 'Tr3093455',
 'Tr3496051',
 'Tr3125175',
 'Tr3126185',
 'Tr3566715',
 'Tr3357745',
 'Tr3337681',
 'Tr3343494',
 'Tr3089774',
 'Tr3262920',
 'Tr3409272',
 'Tr3338781',
 'Id1197753.0',
 'Tr3398589',
 'Tr3038840',
 'Tr3338398',
 'Tr3251652',
 'Id1181194.0',
 'Tr3362639',
 'Tr3142263',
 'Tr3213315',
 'Tr3561865',
 'Tr3296617',
 'Id1323648.0',
 'Tr3140499',
 'Tr3136136',
 'Tr3237049',
 'Tr3236231',
 'Id180197.0',
 'Tr3032413',
 'Tr3146668',
 'Tr3297609',
 'Tr3390570',
 'Id189296.0',
 'Tr3161145',
 'Tr3120317',
 'C110152',
 'Tr3406153',
 'Id1106204.0',
 'Tr3276729',
 'Tr3135849',
 'Tr3270847',
 'Id1466771.0',
 'Tr3444534',
 'Tr3136767',
 'Tr3148628',
 'Tr3210360',
 'Tr3302543',
 'Tr3371862',
 'Tr3367596',
 'Tr3485938',
 'Tr3369975',
 'Tr3216353',
 'Tr2998242',
 'Tr3373647',
 'Tr3443544',
 'Tr3095654',
 'Tr3103602',
 'Tr3334536',
 'Id183328.0',
 'Tr3387971',
 'Tr3199634',
 'Tr3430647',
 'Tr3049677',
 'Tr2988762',
 'Tr3538889',
 'Id1431752.0',
 'Tr3029705',
 'Tr3266280',
 'Tr3016475',
 'Tr3319295',
 'Tr3202101',
 'Tr3033651',
 'Id1213438.0',
 'Tr3557681',
 'Tr3403317',
 'Tr2998951',
 'Tr3367714',
 'Id112475.0',
 'Tr3568356',
 'Tr3422638',
 'Tr3032125',
 'C110201',
 'Id1217627.0',
 'Tr3239103',
 'Tr3051655',
 'Tr3156439',
 'Tr2991648',
 'Tr3143090',
 'Tr3188939',
 'Tr3501886',
 'Tr2990248',
 'Tr3112776',
 'Id193556.0',
 'Id174662.0',
 'Tr3208893',
 'Id1109974.0',
 'Id119374.0',
 'Tr3216108',
 'Tr3488058',
 'Tr3438974',
 'Tr3342804',
 'Id1362534.0',
 'Tr3200462',
 'Tr3411958',
 'Id1393502.0',
 'Tr3044190',
 'Tr3027965',
 'Tr3433980',
 'Id1114123.0',
 'Tr3468148',
 'Tr3463544',
 'Tr2988546',
 'Tr3046854',
 'Tr3060249',
 'Tr3050662',
 'Tr3105540',
 'Tr3395412',
 'Tr3253653',
 'Tr3417490',
 'Tr3045935',
 'Tr2993339',
 'Id1294715.0',
 'Tr3178011',
 'Tr3371179',
 'Tr3256646',
 'Tr3457016',
 'Tr3508165',
 'Tr3567311',
 'Tr3124776',
 'Tr3508415',
 'C16739',
 'Tr3404321',
 'Tr3447163',
 'Id1133616.0',
 'Tr3253190',
 'Tr3344513',
 'Tr3451837',
 'Tr3250658',
 'Tr3348797',
 'Tr3086871',
 'Tr3034071',
 'C115276',
 'Tr3559945',
 'Tr3300415',
 'Tr3389194',
 'Tr3414096',
 'Tr3370033',
 'Tr3125109',
 'Tr3156842',
 'Tr3154555',
 'Tr3004056',
 'Tr3275632',
 'Tr3146133',
 'Tr3365206',
 'Tr3506385',
 'Id1937494.0',
 'Tr3460709',
 'Tr3498368',
 'Id178125.0',
 'Tr3351647',
 'Tr3374731',
 'Tr3073314',
 'Id1139874.0',
 'Tr3491336',
 'Tr3147706',
 'Tr3319892',
 'C11110',
 'Tr3427884',
 'Tr3334941',
 'Tr3305406',
 'Id1179515.0',
 'Tr3375342',
 'Id1167535.0',
 'Tr3529222',
 'Tr3215264',
 'Tr3408820',
 'Id166065.0',
 'Tr3509269',
 'Tr3418319',
 'Tr3180504',
 'Tr3467385',
 'Tr3028819',
 'Tr3281919',
 'Tr3512652',
 'Tr3232947',
 'Tr3218890',
 'Tr3401772',
 'Tr3371225',
 'Tr3473074',
 'Tr3378116',
 'Tr3453871',
 'Id1158392.0',
 'Tr3037535',
 'Tr3051081',
 'Tr2997136',
 'Tr3100126',
 'Tr3386193',
 'Tr3054210',
 'Tr3415038',
 'Id1101358.0',
 'Tr3143755',
 'Id1207714.0',
 'Tr3257137',
 'Tr3299770',
 'C116543',
 'Tr3115080',
 'Tr2990583',
 'Tr3371777',
 'Tr3390162',
 'Tr3426286',
 'Tr3068642',
 'Tr3312269',
 'Id1417511.0',
 'Id116804.0',
 'Id1104048.0',
 'Id179249.0',
 'Tr3535503',
 'Tr3364161',
 'Tr3124748',
 'Id193317.0',
 'Id1419210.0',
 'Tr3351775',
 'Tr3040931',
 'Tr3511258',
 'Id1103481.0',
 'Tr3535487',
 'Tr3112951',
 'Tr3383729',
 'Tr3149034',
 'Tr3206854',
 'Tr3385889',
 'Id1250736.0',
 ...}

In [10]:
print(f'Number of Edges: {transactions_graph.number_of_edges():,.0f}')
print(f'Number of Nodes: {transactions_graph.number_of_nodes():,.0f}')

Number of Edges: 1,781,080
Number of Nodes: 720,154

In [11]:
# taking a look at degeree centrality
top_degrees = dict(sorted(list(transactions_graph.degree), key=lambda x: x[1], reverse=True)[:10])

### Degree Centrality Notes

- All of the top ten most connected nodes are address nodes.

- This isn't too alarming, many businesses would have one address and could have a large volume of transaction traffic.
- The highest degree value is noticably higher than the rest of the values, which does seem suspicious, however this alone is not enough to definitively flag it.
- Will take a look at this valu addr2 == 87 to see if any other insights can be gained from it.

In [12]:
def get_fraud_ratio(target_pairs: dict):
    for key, val in target_pairs.items():
        target_col = 'addr' + key[4]
        lookup_val = float(key[5:])

        fraud_count = train_transaction[train_transaction[target_col] == lookup_val].isFraud.sum()
        total_count = train_transaction[train_transaction[target_col] == lookup_val].isFraud.count()

        print(f'Degree centrality for {target_col} == {lookup_val}: {val}')
        print(f'Fraud ratio for {target_col} == {lookup_val}: {(fraud_count / total_count) * 100:.4f}%')      
        print('---------------------------') 


get_fraud_ratio(top_degrees)

Degree centrality for addr2 == 87.0: 520481
Fraud ratio for addr2 == 87.0: 2.3972%
---------------------------
Degree centrality for addr1 == 299.0: 46335
Fraud ratio for addr1 == 299.0: 2.1258%
---------------------------
Degree centrality for addr1 == 325.0: 42751
Fraud ratio for addr1 == 325.0: 2.5426%
---------------------------
Degree centrality for addr1 == 204.0: 42020
Fraud ratio for addr1 == 204.0: 2.6654%
---------------------------
Degree centrality for addr1 == 264.0: 39870
Fraud ratio for addr1 == 264.0: 1.8259%
---------------------------
Degree centrality for addr1 == 330.0: 26287
Fraud ratio for addr1 == 330.0: 3.1955%
---------------------------
Degree centrality for addr1 == 315.0: 23078
Fraud ratio for addr1 == 315.0: 1.7809%
---------------------------
Degree centrality for addr1 == 441.0: 20827
Fraud ratio for addr1 == 441.0: 2.5592%
---------------------------
Degree centrality for addr1 == 272.0: 20141
Fraud ratio for addr1 == 272.0: 2.8598%
---------------------------
Degree centrality for addr1 == 123.0: 16105
Fraud ratio for addr1 == 123.0: 2.4713%
---------------------------

In [13]:
# list(nx.connected_components(transactions_graph))

### Comments
- It appears that all of the high degree centrality nodes have similar fraud rates hovering in that 2-3%.

- Degree centrality is likely just not a good identifying measure here.
- I will continue to explore other options.

### Exploring connections between components

In [14]:
len_sorted_comps = sorted(nx.connected_components(transactions_graph), key=len, reverse=True)
[len(c) for c in len_sorted_comps]

[716347,
 35,
 26,
 25,
 22,
 21,
 19,
 19,
 19,
 17,
 17,
 16,
 15,
 15,
 15,
 15,
 14,
 14,
 14,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 13,
 12,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 10,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 8,
 8,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

### Issues
- There is obviously an issues here where since one of the componenets is massive and there is a steep drop to the next one.
- Will look at ways to reduce this next and hopefully achieve more meaningful compoonents.

In [15]:
# examing the large component only to see why it is so massive
largest_comp = len_sorted_comps[0]

# getting the degrees for the largest component to see how connected they are
largest_degrees = sorted(list(transactions_graph.degree(largest_comp)), key=lambda x: x[1], reverse=True)

In [16]:
# trimming the graph down to only ndoes with degrees of 150 or lower
trimmed_graph = transactions_graph.copy()
for node, deg in transactions_graph.degree():
    if not node.startswith('Tr') and deg > 75: # if it isn't a transaction and has too high of degree, clip it
        trimmed_graph.remove_node(node)

In [17]:
# sorted([len(c) for c in list(nx.connected_components(trimmed_graph))], reverse=True)

con_comps_trimmed = sorted([c for c in list(nx.connected_components(trimmed_graph))], reverse=True, key=len)

In [18]:
len(con_comps_trimmed[0])

37516

### Looking at alternative clustering methods for better results

In [19]:
common_bridge_attributes = []

for value in list(nx.ego_graph(transactions_graph, 'Tr3474748', radius=2)):
    if not value.startswith('Tr'):
        print(value)
        common_bridge_attributes.append(value)

C17487
Addr1191.0
Addr287.0
Id141467.0

In [20]:
len(list(nx.ego_graph(transactions_graph, 'Tr3474748', radius=2)))

520485

In [21]:
520485 / 4 # ratio of total neighbors to the bridges

# maybe a ratio between 15 and 8 could be interesting

130121.25

- Since transactions can only be connected indirectly, and transacations dominate the negibors wihtin radius 2 of this transaction, thsee attributed must be very common for many transactions.
- It might be worth traversing to all transactions and seeing if there is a smaller number of neighbors connected by differnent bridges.

In [22]:
def find_uncommon_bridges(
        target_graph: nx.Graph, 
        start_point: str, 
        radius: int, 
        primary_prefix: str,
        interesting_finds: list[tuple] = [] # initialized as empty list and accumulated over recurive calls
    ) -> list[tuple]:

    # get the root neighbors list
    root_neighbors = list(nx.ego_graph(target_graph, start_point, radius=radius))
    
    key_transaction, size_of_cluster = start_point, len(root_neighbors)

    # find the common and uncommon bridges
    root_neighbor_bridges = set()
    transactions = set()
    uncommon_bridges = set()
    for node in root_neighbors:
        if not node.startswith(primary_prefix):
            root_neighbor_bridges.add(node)
            continue

        transactions.add(node)
        
    # get ratio of total cluster to the bridge nodes
    ratio = size_of_cluster / len(root_neighbor_bridges)

    # determine if bridges are uncommon by falling in this range
    if ratio <= 15 and ratio >= 8:
        print('found interesting result')
        uncommon_bridges = root_neighbor_bridges.copy()
        
        # append tuple of findings to interesting finds since there is a new observation
        interesting_finds.append((key_transaction, size_of_cluster, uncommon_bridges))
        return interesting_finds # this is the base case to end the BFS

    # if no uncommon bridge is found keep searching all neighbors recursively and updating the interesting finds
    for trans_node in transactions:
        found_bfs = find_uncommon_bridges(target_graph, trans_node, radius, primary_prefix, interesting_finds)
        if len(found_bfs): 
            print('Found interesting result')
            return interesting_finds + found_bfs
        
        # interesting_finds = interesting_finds +
        
    return interesting_finds
    # return a tupel of (key_transaction, size of cluster, uncommon_bridges)

In [23]:
intersting_clusters = find_uncommon_bridges(transactions_graph, 'Tr3474748', 2, 'Tr')

KeyboardInterrupt:

### Creating mappings of components and transactions
- Since the primary interest is transactions components, this provides a map that links together any transaction that are connected through things like similar card use etc.
- Note that these connnections can be inderect where one transaction connects directly through a shared card, and then is further indirectly connected to a third transaction through an attribute shared by the second and third transactions only.

In [97]:
comp_mapppings = {}

for i, comp in enumerate(len_sorted_comps):
    for node in comp:
        comp_mapppings[node] = {
            'comp_id': i,
            'comp_size' : len(len_sorted_comps[i] )
        }

In [151]:
# [{attr: comp_mapppings[attr]} for attr in comp_mapppings if attr[0:2] == 'Tr'][10]
[len(c) for c in len_sorted_comps][0]

# len_sorted_comps[0]

716347

In [119]:
sorted(list(transactions_graph.degree(len_sorted_comps[0])), key=lambda x: x[1], reverse=True)[:100]

[('Addr287.0', 520481),
 ('Addr1299.0', 46335),
 ('Addr1325.0', 42751),
 ('Addr1204.0', 42020),
 ('Addr1264.0', 39870),
 ('Addr1330.0', 26287),
 ('Addr1315.0', 23078),
 ('Addr1441.0', 20827),
 ('Addr1272.0', 20141),
 ('Addr1123.0', 16105),
 ('Addr1126.0', 15243),
 ('Addr1184.0', 15160),
 ('Addr1337.0', 15149),
 ('Addr1191.0', 14979),
 ('C17919', 14932),
 ('C19500', 14162),
 ('Addr1181.0', 13856),
 ('C115885', 10361),
 ('C117188', 10344),
 ('Addr1143.0', 9806),
 ('Addr1476.0', 9478),
 ('Addr1310.0', 8486),
 ('Addr1472.0', 8478),
 ('Addr1327.0', 8425),
 ('Addr1512.0', 8268),
 ('Addr1387.0', 8187),
 ('C115066', 7945),
 ('Addr1433.0', 7831),
 ('Addr1231.0', 7605),
 ('C112695', 7091),
 ('Addr1485.0', 6816),
 ('C112544', 6773),
 ('C16019', 6771),
 ('Addr1269.0', 6404),
 ('C12803', 6141),
 ('Addr1205.0', 5725),
 ('C17585', 5334),
 ('Addr1225.0', 5323),
 ('Addr1251.0', 5216),
 ('C110616', 5172),
 ('C112839', 5129),
 ('Addr1494.0', 5065),
 ('Addr1220.0', 5041),
 ('Addr1226.0', 4867),
 ('Addr1498.0', 4744),
 ('Addr1177.0', 4674),
 ('C13154', 4614),
 ('C12616', 4410),
 ('C118132', 4209),
 ('C19633', 4158),
 ('C115497', 3977),
 ('C116132', 3929),
 ('C12884', 3873),
 ('Addr1203.0', 3808),
 ('C116075', 3748),
 ('C111207', 3693),
 ('Addr1420.0', 3581),
 ('C110112', 3560),
 ('C17508', 3490),
 ('Addr1110.0', 3220),
 ('Addr1436.0', 3169),
 ('C110057', 3166),
 ('C112501', 3152),
 ('Addr260.0', 3084),
 ('C17826', 3006),
 ('C116659', 2988),
 ('Addr1469.0', 2940),
 ('C112577', 2891),
 ('C15812', 2818),
 ('C17664', 2792),
 ('C17861', 2774),
 ('C16530', 2714),
 ('C14461', 2686),
 ('C18320', 2632),
 ('C15033', 2604),
 ('C17207', 2578),
 ('C115063', 2522),
 ('C110486', 2505),
 ('C110023', 2428),
 ('C17815', 2411),
 ('C19112', 2364),
 ('Addr1324.0', 2173),
 ('C116560', 2080),
 ('C19026', 2076),
 ('C116136', 2069),
 ('C14806', 2067),
 ('C113832', 2062),
 ('C17676', 2038),
 ('Addr1444.0', 2033),
 ('Addr1170.0', 2001),
 ('C112932', 1998),
 ('C11444', 1964),
 ('C14436', 1947),
 ('C111839', 1940),
 ('C117399', 1916),
 ('C12772', 1898),
 ('C12455', 1799),
 ('C11675', 1790),
 ('C114290', 1767),
 ('Addr1343.0', 1734)]